apiVersion: v2
name: elk
description: ELK Stack for BankApp logging and monitoring
type: application
version: 0.1.0

dependencies:
  - name: elasticsearch
    version: 22.1.6
    repository: https://raw.githubusercontent.com/bitnami/charts/refs/heads/archive-full-index/bitnami/
    condition: elasticsearch.enabled

  - name: logstash
    version: 7.0.11
    repository: https://raw.githubusercontent.com/bitnami/charts/refs/heads/archive-full-index/bitnami/
    condition: logstash.enabled

  - name: kibana
    version: 12.1.10
    repository: https://raw.githubusercontent.com/bitnami/charts/refs/heads/archive-full-index/bitnami/
    condition: kibana.enabled