spring:
  application:
    name: front
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        default-context: apps
        format: KEY_VALUE
        fail-fast: false
      discovery:
        enabled: true
  config:
    import:
      - "optional:consul:"

logging:
  level:
    org.springframework.boot.context.config: debug
    org.springframework.cloud.consul: debug
    org.springframework.cloud.bootstrap: debug
    com.ecwid.consul: debug
    ru.yandex.front.feign.CashClient: debug
    ru.yandex.front.feign.AccountsClient: trace
    ru.yandex.front.feign.TransferClient: debug

    org.springframework.security: trace
    org.springframework.web: DEBUG
    org.springframework.web.cors: trace
    ru.yandex.accounts.accounts-serv: TRACE
    feign: DEBUG