spring:
  application:
    name: front
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 15000
            loggerLevel: full
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        default-context: apps
        format: KEY_VALUE
        fail-fast: false
      discovery:
        enabled: true
  config:
    import:
      - "optional:consul:"
management:
  zipkin:
    tracing:
      endpoint:  http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,tracing"
logging:
  level:
    ru.yandex.front.feign.CashClient: debug
    ru.yandex.front.feign.AccountsClient: trace
    ru.yandex.front.feign.TransferClient: debug
    org.springframework.cloud.circuitbreaker: DEBUG
    io.github.resilience4j: DEBUG
