spring:
  application:
    name: front
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        default-context: apps
        format: KEY_VALUE
        fail-fast: false
      discovery:
        enabled: true
  config:
    import:
      - "optional:consul:"

logging:
  level:
    ru.yandex.front.feign.CashClient: debug
    ru.yandex.front.feign.AccountsClient: trace
    ru.yandex.front.feign.TransferClient: debug
    org.springframework.cloud.circuitbreaker: DEBUG
    io.github.resilience4j: DEBUG
