apiVersion: v2
name: postgresql
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "18.1.8"

dependencies:
  - name: postgresql
    version: 18.1.8
    repository: https://raw.githubusercontent.com/bitnami/charts/refs/heads/archive-full-index/bitnami/
    condition: postgresql.enabled
