accounts:
  secrets:
    enabled: true
    spring:
      datasource:
        username: "bankapp"
        password: "bankapp"
      liquibase:
        username: "bankapp"
        password: "bankapp"
      security:
        oauth2:
          client:
            registration:
              keycloak:
                client-secret: "vRBqHqy5rIgQjqHLk4ntrFMflfZZ1V5Y"

cash:
  secrets:
    enabled: true
    spring:
      security:
        oauth2:
          client:
            registration:
              keycloak:
                client-secret: "VKgaEyKXFsc5QJJrtDolB2Luv7KyeXth"

transfer:
  secrets:
    enabled: true
    spring:
      security:
        oauth2:
          client:
            registration:
              keycloak:
                client-secret: "tFVIAzOu86RAkgbIzmZgEkeCoOYk74w1"

notifications:
  secrets:
    enabled: true
    spring:
      security:
        oauth2:
          client:
            registration:
              keycloak:
                client-secret: "zwNU03EpVjSvqo7UpsJdghw6v0EVe0hC"
      mail:
        password: "irwlzrzewdogocpw"
        username: "app.oldixi@yandex.ru"

front:
  spring:
    security:
      oauth2:
        client:
          registration:
            keycloak:
              client-secret: "moY8OTX4GbDI5AwmholMgAXT0aJDCSpf"

