spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        default-context: apps
        format: KEY_VALUE
        fail-fast: false
      discovery:
        enabled: true
  config:
    import:
      - "optional:consul:"

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Временно включите все эндпоинты для диагностики

logging:
  level:
    org.springframework.boot.context.config: trace
    org.springframework.cloud.gateway: trace
    org.springframework.boot.actuate: debug
    org.springframework.cloud.consul: trace
    org.springframework.cloud.bootstrap: trace
    com.ecwid.consul: trace

