spring:
  cloud:
    consul:
      host: consul
      port: 8500
      config:
        enabled: true
        default-context: apps
        format: KEY_VALUE
        fail-fast: false
      discovery:
        enabled: true
        register: true
        instance-id: ${spring.application.name}:${random.value}
        service-name: ${spring.application.name}

logging:
  level:
    org.springframework.cloud.consul: info
    org.springframework.cloud.gateway: debug