spring:
  application:
    name: cash
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 15000
            loggerLevel: full
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        default-context: apps
        format: KEY_VALUE
        fail-fast: false
      discovery:
        enabled: true
  config:
    import:
      - "optional:consul:"
management:
  zipkin:
    tracing:
      endpoint:  http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,tracing"
logging:
  level:
    org.springframework.boot.context.config: info
    org.springframework.cloud.consul: info
    org.springframework.cloud.bootstrap: info
    com.ecwid.consul: info