spring:
  application:
    name: accounts
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        default-context: apps
        format: KEY_VALUE
        fail-fast: false
      discovery:
        enabled: true
  config:
    import:
      - "optional:consul:"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bankapp

logging:
  level:
    org.springframework.boot.context.config: info
    org.springframework.cloud.consul: info
    org.springframework.cloud.bootstrap: info
    com.ecwid.consul: info