spring:
  application:
    name: accounts
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        default-context: apps
        format: KEY_VALUE
        fail-fast: false
      discovery:
        enabled: true
  config:
    import:
      - "optional:consul:"
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        interceptor.classes: ru.yandex.accounts.serv.accounts.config.KafkaLoggingInterceptor
    admin:
      properties:
        bootstrap.servers: kafka:9092
      auto-create: true
    retry:
      topic:
        enabled: true
        attempts: 5
        backoff:
          delay: 5

logging:
  level:
    org.springframework.boot.context.config: info
    org.springframework.cloud.consul: info
    org.springframework.cloud.bootstrap: info
    com.ecwid.consul: info