replicaCount: 1
global:
  namespace: bankapp
  ingress:
    enabled: true
    className: "nginx"
    host: bankapp.local
  spring:
    security:
      oauth2:
        client:
          registration:
            keycloak:
              provider: keycloak
              authorizationGrantType: client_credentials
              scope: openid,profile,email
              clientAuthenticationMethod: client_secret_basic
          provider:
            keycloak:
              issuerUri: http://keycloak/realms/bankapp
        resourceserver:
          jwt:
            issuerUri: http://keycloak/realms/bankapp
            jwkSetUri: http://keycloak/realms/bankapp/protocol/openid-connect/certs
    cloud:
      kubernetes:
        discovery:
          enabled: true
          allNamespaces: true
          includeNotReadyAddresses: true
          waitForReadyAddresses: true
          timeout: 30s
  feign:
    circuitbreaker:
      enabled: true
    config:
      default:
        retryer: feign.Retryer.Default
