apiVersion: v2
name: accounts
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.0.1"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
    alias: common
