apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "front.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.rules }}
rules:
  {{- toYaml . | nindent 8 }}
{{- end }}