apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "front.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "front.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}